### ISSUE TITLE
Error: A template expression is not allowed in this context

### ISSUE THREAD

**Issue by Marcus-James-Adams** [YannickRe/azuredevops-buildagents#1]
```
parameters:
- name: image_type
  displayName: Build Agent Image
  type: string
  default: windows2019
  values:
  - windows2019
  - ubuntu2004
- name: variable_group
  displayName: Variable Group
  type: string
  default: BuildAgents
- name: agent_pool
  displayName: Agent Pool
  type: string
  default: MyPool

trigger: none

pool: ${{ parameters.agent_pool }}
```
On validating I get 

/buildagent-generation.yml (Line: 20, Col: 7): A template expression is not allowed in this context

if however, I change pool to be a hardcoded value it runs ok  eg (pool: MyPool)
