### ISSUE TITLE
What is the best way to customize the created VM scale set

### ISSUE THREAD

**Issue by Arash-Sabet** [YannickRe/azuredevops-buildagents#38]
I have successfully created an Ubuntu 2204 scale set and the build agent is working fine. when it comes to compiling and building our .NET application.  We also want to run our integration tests which depend on the presence of Azurite and a NoSQL database on the hosting machine. I tried to run the following yaml file to install Azurite but I kept getting the error message of **"The remote provider was unable to process the request"** which I cannot justify why it should get me this error.

```yml
pr: none
trigger: none

pool:
  vmImage: myubuntu2204agent

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Attempting to install Azurite'
      npm install -g azurite
```

The question is that should I clone Microsoft's [runner images](https://github.com/actions/runner-images) repo, and augment it by implementing a script to have both Azurite and the NoSQL database included in the VM image or the YAML file above should be sufficient to install Azurite. If so, why I keep getting the error message?
