### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by andrejabuildingminds** [YannickRe/azuredevops-buildagents#80]
Hello, when calling a buildagent-generation-template.yml in my pipeline, I get this error:
```
Encountered error(s) while parsing pipeline YAML:
/buildagent-generation-template.yml@azuredevops-buildagents (Line: 44, Col: 1): Unexpected value 'stages'
```

**Comment by YannickRe** [comment]
I currently cannot reproduce this issue. Are you starting your pipeline with `build-generation.yml`? You can't start directly with `build-generation-template.yml`, it's meant to be used by a top-level pipeline.

**Comment by andrejabuildingminds** [comment]
I am now starting the pipeline with `buildagent-generation.yml` and I get the similar errors:
```
/buildagent-generation.yml@azuredevops-buildagents (Line: 35, Col: 1): Unexpected value 'trigger'
/buildagent-generation.yml@azuredevops-buildagents (Line: 37, Col: 1): Unexpected value 'stages'
```

**Comment by YannickRe** [comment]
You'll have to give me a bit more to work on this, because I currently can't reproduce this... It all works on my end.
Can you get me a screenshot of your pipeline, and the different steps, and ... ?

**Comment by YannickRe** [comment]
Ok, now I understand what you are trying to do.
Try this pipeline:
```
trigger:
- none

resources:
  repositories:
  - repository: azuredevops-buildagents
    type: github
    name: YannickRe/azuredevops-buildagents
    endpoint: github.com_andrejabuildingminds
    ref: refs/heads/main

stages:
- template: buildagent-generation-template.yml@azuredevops-buildagents
  parameters: 
    image_type: ${{ parameters.image_type }}
    runner_images_version: ${{ parameters.runner_images_version }}
    variable_group_name: ${{ parameters.variable_group_name }}
    agent_pool: ${{ parameters.agent_pool }}
    repository_base_path: azuredevops-buildagents
    update_type: ${{ parameters.update_type }}

stages:
- template: buildagent-generation-template.yml@azuredevops-buildagents
  parameters: 
    image_type: ubuntu2204
    runner_images_version: alpha
    variable_group_name: ubuntu2204-agentpool
    agent_pool: ubuntu2204-agentpool
    repository_base_path: azuredevops-buildagents
    update_type: galleryvm
```
